### Importing the EIA module

In [5]:
import eia

### Importing libraries for Data Visualization

In [6]:
import chart_studio.plotly as py
import plotly.offline as po
import plotly.graph_objs as pg
import numpy as np
import pandas as pd

In [7]:
import warnings
warnings.filterwarnings("ignore")

### Loading Data using the eia.loaders.load_dataframe method
We will analyze the 'state-electricity-profiles-emissions-by-state-by-fuel' file and try to find some interesting insights from the data.

In [ ]:
df = eia.loaders.load_dataframe(data='state-electricity-profiles-emissions-by-state-by-fuel')

In [19]:
df = pd.read_csv('../../../../Downloads/emissions-by-state-by-fuel_data.csv')

In [20]:
df.head()

Unnamed: 0 period stateid stateDescription fuelid fuelDescription  \
0         0.0   2020      AL          Alabama    COL            Coal   
1         1.0   2020      WY          Wyoming    ALL           Total   
2         2.0   2020      WY          Wyoming    PET       Petroleum   
3         3.0   2020      WY          Wyoming    OTH           Other   
4         4.0   2020      WY          Wyoming     NG     Natural Gas   

  so2-rate-lbs-mwh so2-short-tons nox-rate-lbs-mwh nox-short-tons  \
0              NaN           3164              NaN           8315   
1              1.3          27112              1.6          34243   
2              NaN              6              NaN             21   
3              NaN              9              NaN           3968   
4              NaN              6              NaN           2371   

  co2-rate-lbs-mwh co2-thousand-metric-tons   so2-rate-lbs-mwh-units  \
0              NaN                    21156  pounds per megawatthour   
1           1969.0                    37594  pounds per megawatthour   
2              NaN                       36  pounds per megawatthour   
3              NaN                        0  pounds per megawatthour   
4              NaN                     1072  pounds per megawatthour   

  so2-short-tons-units   nox-rate-lbs-mwh-units nox-short-tons-units  \
0           short tons  pounds per megawatthour           short tons   
1           short tons  pounds per megawatthour           short tons   
2           short tons  pounds per megawatthour           short tons   
3           short tons  pounds per megawatthour           short tons   
4           short tons  pounds per megawatthour           short tons   

    co2-rate-lbs-mwh-units co2-thousand-metric-tons-units  
0  pounds per megawatthour           thousand metric tons  
1  pounds per megawatthour           thousand metric tons  
2  pounds per megawatthour           thousand metric tons  
3  pounds per megawatthour           thousand metric tons  
4  pounds per megawatthour           thousand metric tons

In [21]:
df.loc[0]

Unnamed: 0                                            0.0
period                                               2020
stateid                                                AL
stateDescription                                  Alabama
fuelid                                                COL
fuelDescription                                      Coal
so2-rate-lbs-mwh                                      NaN
so2-short-tons                                       3164
nox-rate-lbs-mwh                                      NaN
nox-short-tons                                       8315
co2-rate-lbs-mwh                                      NaN
co2-thousand-metric-tons                            21156
so2-rate-lbs-mwh-units            pounds per megawatthour
so2-short-tons-units                           short tons
nox-rate-lbs-mwh-units            pounds per megawatthour
nox-short-tons-units                           short tons
co2-rate-lbs-mwh-units            pounds per megawatthour
co2-thousand-m

In [22]:
df['period'].unique()

array(['2020', '2018', '2017', '2016', '2015', '2014', '2013', '2012',
       '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004',
       '2003', '2002', '2001', '2000', 'period', '1999', '1998', '1997',
       '1996', '1995', '1994', '1993', '1992', '1991', '1990'],
      dtype=object)

In [24]:
df['stateid'].unique()

array(['AL', 'WY', 'WV', 'WI', 'UT', 'US', 'TX', 'WA', 'VT', 'VA', 'TN',
       'NM', 'RI', 'PA', 'OR', 'OK', 'SD', 'SC', 'OH', 'NY', 'NV', 'MI',
       'ME', 'ND', 'NC', 'MT', 'MS', 'NJ', 'NH', 'NE', 'MO', 'MN', 'MD',
       'HI', 'GA', 'KY', 'KS', 'IN', 'IL', 'MA', 'LA', 'ID', 'IA', 'AK',
       'CT', 'CO', 'CA', 'AZ', 'FL', 'DE', 'DC', 'AR', 'stateid'],
      dtype=object)

In [25]:
len(df['stateid'].unique())

53

In [26]:
df['stateDescription'].unique()

array(['Alabama', 'Wyoming', 'West Virginia', 'Wisconsin', 'Utah',
       'United States', 'Texas', 'Washington', 'Vermont', 'Virginia',
       'Tennessee', 'New Mexico', 'Rhode Island', 'Pennsylvania',
       'Oregon', 'Oklahoma', 'South Dakota', 'South Carolina', 'Ohio',
       'New York', 'Nevada', 'Michigan', 'Maine', 'North Dakota',
       'North Carolina', 'Montana', 'Mississippi', 'New Jersey',
       'New Hampshire', 'Nebraska', 'Missouri', 'Minnesota', 'Maryland',
       'Hawaii', 'Georgia', 'Kentucky', 'Kansas', 'Indiana', 'Illinois',
       'Massachusetts', 'Louisiana', 'Idaho', 'Iowa', 'Alaska',
       'Connecticut', 'Colorado', 'California', 'Arizona', 'Florida',
       'Delaware', 'District of Columbia', 'Arkansas', 'stateDescription'],
      dtype=object)

In [27]:
df['fuelDescription'].unique()

array(['Coal', 'Total', 'Petroleum', 'Other', 'Natural Gas',
       'fuelDescription'], dtype=object)

### Let's study the SO2, NOX and CO2 emissions for the fuel : Total.
### We will analyze the data for each state from the year 1990 to 2020.

In [28]:
emissions_per_state = {}
for entry in df.values:
    if entry[1] == 2020 and entry[5] == 'Total':
        emissions_per_state[entry[2]] = (entry[7], entry[9], entry[11])

In [29]:
emissions_per_state

{}

In [30]:
df.values[0]

array([0.0, '2020', 'AL', 'Alabama', 'COL', 'Coal', nan, '3164', nan,
       '8315', nan, '21156', 'pounds per megawatthour', 'short tons',
       'pounds per megawatthour', 'short tons', 'pounds per megawatthour',
       'thousand metric tons'], dtype=object)

In [31]:
df.keys

<bound method NDFrame.keys of       Unnamed: 0 period stateid stateDescription fuelid fuelDescription  \
0            0.0   2020      AL          Alabama    COL            Coal   
1            1.0   2020      WY          Wyoming    ALL           Total   
2            2.0   2020      WY          Wyoming    PET       Petroleum   
3            3.0   2020      WY          Wyoming    OTH           Other   
4            4.0   2020      WY          Wyoming     NG     Natural Gas   
...          ...    ...     ...              ...    ...             ...   
7560      2559.0   1990      WY          Wyoming    COL            Coal   
7561      2560.0   1990      WY          Wyoming     NG     Natural Gas   
7562      2561.0   1990      WY          Wyoming    OTH           Other   
7563      2562.0   1990      WY          Wyoming    PET       Petroleum   
7564      2563.0   1990      WY          Wyoming    ALL           Total   

     so2-rate-lbs-mwh so2-short-tons nox-rate-lbs-mwh nox-short-tons 

### SO2 Emissions

In [37]:
so2 = {}
for year in df['period'].unique():
    if year != 'period':
        d = {}
        for i in df.values:
            if i[1] == year and i[5] == 'Total':
                d[i[2]] = i[6]
        y = int(year)
        so2[y] = d

In [43]:
so2[1990]

{'AR': '4.4',
 'CT': '3.3',
 'DC': '14.1',
 'DE': '22.5',
 'FL': '10.6',
 'AZ': '4.0',
 'CA': '1.1',
 'CO': '6.3',
 'AK': '7.4',
 'AL': '14.0',
 'GA': '18.2',
 'IA': '13.4',
 'ID': '2.0',
 'IL': '14.5',
 'LA': '3.2',
 'MA': '11.7',
 'MD': '17.9',
 'IN': '27.8',
 'KS': '5.1',
 'KY': '24.4',
 'HI': '8.0',
 'MN': '5.2',
 'MO': '26.9',
 'ND': '10.9',
 'NE': '4.8',
 'NH': '10.7',
 'NJ': '3.9',
 'MS': '10.5',
 'MT': '1.5',
 'NC': '9.4',
 'ME': '7.3',
 'MI': '8.4',
 'NV': '5.5',
 'NY': '6.8',
 'SC': '5.6',
 'SD': '9.7',
 'OH': '34.7',
 'OK': '4.8',
 'OR': '0.4',
 'PA': '15.6',
 'RI': '3.3',
 'NM': '4.1',
 'TN': '22.1',
 'VA': '9.1',
 'VT': '0.0',
 'WA': '1.5',
 'TX': '4.5',
 'US': '11.2',
 'UT': '1.9',
 'WI': '14.7',
 'WV': '24.3',
 'WY': '5.5'}

In [40]:
layout = dict(geo = {'scope':'usa'})

In [45]:
years

['1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2020']

In [71]:
years = so2.keys()
data_slider = []
for year in years:

    data_each_yr = dict(
                        type='choropleth',
                        locations = list(so2[year].keys()),
                        z=list(so2[year].values()),
                        locationmode='USA-states',
                        # colorscale = scl,
                        colorbar= {'title':'# Sightings'}
                        )

    data_slider.append(data_each_yr)

steps = []
for i in range(len(data_slider)):
    step = dict(method='restyle',
                args=['visible', [False] * len(data_slider)],
                label='Year {}'.format(i + 1990))
    step['args'][1][i] = True
    steps.append(step)

sliders = [dict(active=0, pad={"t": 1}, steps=steps)]

layout = dict(title ='SO2 Emissions Statewise since 1990 to 2020', geo=dict(scope='usa',
                       projection={'type': 'albers usa'}), sliders=sliders)

fig1 = dict(data=data_slider, layout=layout)
po.iplot(fig1)


In [79]:
pg.Figure.write_html(fig1,'SO2_Emmissions.html')

### NOX Emissions

In [65]:
nox = {}
for year in df['period'].unique():
    if year != 'period':
        d = {}
        for i in df.values:
            if i[1] == year and i[5] == 'Total':
                d[i[2]] = i[8]
        y = int(year)
        nox[y] = d

In [66]:
nox[2020]

{'WY': '1.6',
 'WV': '1.1',
 'WI': '0.8',
 'UT': '1.7',
 'US': '0.7',
 'TX': '0.7',
 'WA': '0.2',
 'VT': '1.1',
 'VA': '0.4',
 'TN': '0.3',
 'NM': '0.8',
 'RI': '0.8',
 'PA': '0.4',
 'OR': '0.5',
 'OK': '0.5',
 'SD': '0.2',
 'SC': '0.3',
 'OH': '0.9',
 'NY': '0.4',
 'NV': '0.5',
 'MI': '1.2',
 'ME': '1.1',
 'ND': '1.5',
 'NC': '0.7',
 'MT': '0.9',
 'NJ': '0.3',
 'NH': '0.2',
 'NE': '1.1',
 'MS': '0.5',
 'MO': '1.5',
 'MN': '0.7',
 'MD': '0.3',
 'HI': '3.6',
 'GA': '0.6',
 'KY': '1.0',
 'KS': '0.5',
 'IN': '1.4',
 'IL': '0.3',
 'MA': '0.9',
 'LA': '1.2',
 'ID': '0.5',
 'IA': '0.6',
 'AL': '0.3',
 'AK': '6.9',
 'CT': '0.3',
 'CO': '0.7',
 'CA': '0.8',
 'AZ': '0.5',
 'FL': '0.4',
 'DE': '0.6',
 'DC': '5.7',
 'AR': '0.6'}

In [72]:
years = nox.keys()

data_slider = []
for year in years:

    data_each_yr = dict(
                        type='choropleth',
                        locations = list(nox[year].keys()),
                        z=list(nox[year].values()),
                        locationmode='USA-states',
                        # colorscale = scl,
                        colorbar= {'title':'# Sightings'})

    data_slider.append(data_each_yr)

steps = []
for i in range(len(data_slider)):
    step = dict(method='restyle',
                args=['visible', [False] * len(data_slider)],
                label='Year {}'.format(i + 1990))
    step['args'][1][i] = True
    steps.append(step)

sliders = [dict(active=0, pad={"t": 1}, steps=steps)]

layout = dict(title ='NOX Emissions Statewise since 1990 to 2020', geo=dict(scope='usa',
                       projection={'type': 'albers usa'}),
              sliders=sliders)

fig2 = dict(data=data_slider, layout=layout)
po.iplot(fig2)

In [80]:
pg.Figure.write_html(fig2,'NOX_Emmissions.html')

### CO2 Emissions

In [68]:
co2 = {}
for year in df['period'].unique():
    if year != 'period':
        d = {}
        for i in df.values:
            if i[1] == year and i[5] == 'Total':
                d[i[2]] = i[10]
        y = int(year)
        co2[y] = d

In [73]:

years = co2.keys()
scl = [[0.0, '#ffffff'],[0.2, '#b4a8ce'],[0.4, '#8573a9'],
       [0.6, '#7159a3'],[0.8, '#5732a1'],[1.0, '#2c0579']] # purples

data_slider = []
for year in years:

    data_each_yr = dict(
                        type='choropleth',
                        locations = list(co2[year].keys()),
                        z=list(co2[year].values()),
                        locationmode='USA-states',
                        #colorscale = scl,
                        colorbar= {'title':'# Sightings'})

    data_slider.append(data_each_yr)

steps = []
for i in range(len(data_slider)):
    step = dict(method='restyle',
                args=['visible', [False] * len(data_slider)],
                label='Year {}'.format(i + 1990))
    step['args'][1][i] = True
    steps.append(step)

sliders = [dict(active=0, pad={"t": 1}, steps=steps)]

layout = dict(title ='CO2 Emissions Statewise since 1990 to 2020', geo=dict(scope='usa',
                       projection={'type': 'albers usa'}),
              sliders=sliders)

fig3 = dict(data=data_slider, layout=layout)
po.iplot(fig3)

In [81]:
pg.Figure.write_html(fig3,'CO2_Emmissions.html')

In [26]:
df['so2-short-tons'[[]]].isnull().sum()

0

In [27]:
df['nox-short-tons'].isnull().sum()

0

In [28]:
a = np.array(df['so2-short-tons'])
b = np.array(df['nox-short-tons'])
c = np.array(df['co2-thousand-metric-tons'])

In [29]:
print(np.corrcoef(a,b))
print(np.corrcoef(a,c))
print(np.corrcoef(b,c))

[[1.         0.92468142]
 [0.92468142 1.        ]]
[[1.         0.78789815]
 [0.78789815 1.        ]]
[[1.         0.81273815]
 [0.81273815 1.        ]]


In [30]:
df_ = df.groupby(['fuelDescription'])

In [31]:
a = np.array(df_['so2-short-tons'])
b = np.array(df_['nox-short-tons'])
c = np.array(df_['co2-thousand-metric-tons'])

In [32]:
a_coal = a[0][1]
a_coal

1        474527
6        591936
15       100454
20       554692
25       609416
         ...   
4953    1022707
4958     664657
4964    1193241
4967    1485827
4972      91350
Name: so2-short-tons, Length: 995, dtype: int64

In [33]:
b_coal = b[0][1]
b_coal

1       120703
6       214362
15       38719
20      207984
25      224054
         ...  
4953    242740
4958    114016
4964    375194
4967    580934
4972     54169
Name: nox-short-tons, Length: 995, dtype: int64

In [34]:
c_coal = c[0][1]
c_coal

1        76742
6        69417
15       40819
20       66054
25       71267
         ...  
4953    127713
4958    110910
4964    122750
4967    122506
4972     65477
Name: co2-thousand-metric-tons, Length: 995, dtype: int64

In [35]:
print(np.corrcoef(a_coal,b_coal))
print(np.corrcoef(a_coal,c_coal))
print(np.corrcoef(b_coal,c_coal))

[[1.         0.91696327]
 [0.91696327 1.        ]]
[[1.         0.79698079]
 [0.79698079 1.        ]]
[[1.         0.75232828]
 [0.75232828 1.        ]]


In [36]:
for i,fuel in enumerate(df['fuelDescription'].unique()):
    a_ = a[i][1]
    b_ = b[i][1]
    c_ = c[i][1]
    
    print(a[i][0])
    print(np.corrcoef(a_,b_))
    print(np.corrcoef(a_,c_))
    print(np.corrcoef(b_,c_))

Coal
[[1.         0.91696327]
 [0.91696327 1.        ]]
[[1.         0.79698079]
 [0.79698079 1.        ]]
[[1.         0.75232828]
 [0.75232828 1.        ]]
Natural Gas
[[1.         0.64178898]
 [0.64178898 1.        ]]
[[1.         0.84969985]
 [0.84969985 1.        ]]
[[1.         0.81143666]
 [0.81143666 1.        ]]
Other
[[1.         0.51395626]
 [0.51395626 1.        ]]
[[1.         0.13285878]
 [0.13285878 1.        ]]
[[1.         0.64581142]
 [0.64581142 1.        ]]
Petroleum
[[1.         0.90382125]
 [0.90382125 1.        ]]
[[1.        0.9044743]
 [0.9044743 1.       ]]
[[1.        0.9110826]
 [0.9110826 1.       ]]
Total
[[1.         0.91319382]
 [0.91319382 1.        ]]
[[1.         0.73113509]
 [0.73113509 1.        ]]
[[1.         0.73141307]
 [0.73141307 1.        ]]
